

//auth login check
post http://127.0.0.1:8000/api/login_check
content-type: application/json

{
    "username": "nico.riot@free.fr",
    "password": "pass"
}

###


//recup des messages
get http://127.0.0.1:8000/api/messages
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTk2Nzc2ODYsImV4cCI6MTU5OTY4MTI4Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibmljby5yaW90QGZyZWUuZnIifQ.vX6aEboiT4V3An4NckDlGIc4ZwXzrjJDDx8VqZxg6tx0k6kSf8UDo-x8197JBgzcjIDpooX_EblezX8vuVp33nfNWkLWujqHlfv9c7evXCHZ_vpUR5sYvI-NhEVEEkhnVtJmUMsynNkTnFyEWi5uO6oAPyguE7Aj8lws6inGHHf4OhZsjkcvg0YR5WcckNl4zJF0HeDmmbzh8fPPovd--Kk00T9S3RhInbWCj0cAG79FHl5VDOdICCfDXOwDbt6wy2dQiQofLhxftrXOJdTrj-JY9z1xiup-SRIYBgkPIlCvOJjNPYXDNYv_WQ4GDBJeRfNEDA52l-NLOhEUdylG8es2weoE6cCbaljouiMJVhu9w_CJ6V-B6kyuf75fk5LmMLp1pXllYaUsitqP5xFwDoD_YgTBWPIIJmtVM7NWwiRWQ6ydftAmYwe_pUNxd4UnLBnDW60lsHpQjoprwTbmn0FsTx5Nj6eKfWLw7jwPvpP0MnyoLglhO5dvWL8JzQSn-Q_NhuVTO2BjUiqK8LFS4qC0eS13-YTvpnUvUHbNFNdMaGna4QNszT6msceDoz2DKRlF69ZDeiR9z3oYrGK7mvGLsCSrBOj20kmfJv33Ve_yX9Lj4iq9LxNf6ZKeJVLIzArnAPSopl65YZy5tGlAc2GIAWFkxdoltMe-v-BznNs

###

delete http://127.0.0.1:8000/api/messages/46
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTk2Nzc2ODYsImV4cCI6MTU5OTY4MTI4Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibmljby5yaW90QGZyZWUuZnIifQ.vX6aEboiT4V3An4NckDlGIc4ZwXzrjJDDx8VqZxg6tx0k6kSf8UDo-x8197JBgzcjIDpooX_EblezX8vuVp33nfNWkLWujqHlfv9c7evXCHZ_vpUR5sYvI-NhEVEEkhnVtJmUMsynNkTnFyEWi5uO6oAPyguE7Aj8lws6inGHHf4OhZsjkcvg0YR5WcckNl4zJF0HeDmmbzh8fPPovd--Kk00T9S3RhInbWCj0cAG79FHl5VDOdICCfDXOwDbt6wy2dQiQofLhxftrXOJdTrj-JY9z1xiup-SRIYBgkPIlCvOJjNPYXDNYv_WQ4GDBJeRfNEDA52l-NLOhEUdylG8es2weoE6cCbaljouiMJVhu9w_CJ6V-B6kyuf75fk5LmMLp1pXllYaUsitqP5xFwDoD_YgTBWPIIJmtVM7NWwiRWQ6ydftAmYwe_pUNxd4UnLBnDW60lsHpQjoprwTbmn0FsTx5Nj6eKfWLw7jwPvpP0MnyoLglhO5dvWL8JzQSn-Q_NhuVTO2BjUiqK8LFS4qC0eS13-YTvpnUvUHbNFNdMaGna4QNszT6msceDoz2DKRlF69ZDeiR9z3oYrGK7mvGLsCSrBOj20kmfJv33Ve_yX9Lj4iq9LxNf6ZKeJVLIzArnAPSopl65YZy5tGlAc2GIAWFkxdoltMe-v-BznNs

