

//auth login check
post http://127.0.0.1:8000/api/login_check
content-type: application/json

{
    "username": "nico.riot@free.fr",
    "password": "pass"
}

###


//recup des messages
get http://127.0.0.1:8000/api/messages
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTg1NDYyNTEsImV4cCI6MTU5ODU0OTg1MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibmljby5yaW90QGZyZWUuZnIifQ.yxTunZIb7BE312uNT1LAQsbR4Lcr8J96M0dW5J4hYepAlCdeL9CWEKfR8Mfa44HYz7bkCx3E0wJ9PBrwzW6mpb2NHVeyT4vcTlbiUsV7J-SHP1RP_UcjwjnX0PHkzh40O0CUk_GuaHZFz0ZCUZjKxWlbqzd74SyhEDsjHGICPwiDp5LKqFiZXayWyrCgyQ4MtqHj1cx6j6btpnxU1TjRBriPeV-A5EltDIZVzmZWUc0aiKa4vUw-DMLw75sd_Bh7CgNSKupv60aVk_b9y-rTb5FpATqZ38dlJzwsTQGUo17hk_gC1F2SoVQHhw6FlOqLxILWjmH9f2VFB9-pl85XLFiMshkCPKI2GGYKxipU2B9iQ2vnIuyR33vhObDtpN6rQdPgHwryjV0v1JvdxieI6D8JUgi-SmjS6WG6Q1zZs4sK9PyBx_TwDhntSvLWyEq-onj5vaSDc8lkaCMa6CY9IUFflij75rPBAwPkyTDXPjRNlUczI9hRveRN-fMdK77mH3A_nvnERv6QgrFdVxBbeL3VZrQPf-rpForWvu3-nTz5zsOfHlG8Flfc_3jwMjjUTxWLAVcQL0M6DIKR9PuNNqM7EZ5U6PfZffH0iULm2iOK-8JlwPp976zxfXfD3doBHI00CZxTyrGOHbTANmIFTS1ajKb9k4F_BPxR4dUwoOg
